name: ci

on:
  workflow_dispatch:
  push:

jobs:
  qemu:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Install ldid
        uses: MOZGIII/install-ldid-action@v1
        with:
          tag: v2.1.5-procursus2
        
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: install pkg
        run: |
          cd lapce-volar
          npm install
          npx pkg vue-language-server.js --out-path ${{ github.workspace }}/lapce-volar/dist --target macos-x64,macos-arm64,linux-x64,linux-arm64,win-x64,win-arm64
          tar -zcvf dist.tar.gz ./dist
      - name: ls name
        run: ls

      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: volar
          path: ${{ github.workspace }}/lapce-volar/dist.tar.gz
          retention-days: 1
