# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the workflow will run
on:
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  linux:
    runs-on: ubuntu-latest
    container: ubuntu:18.04
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2.0.0
        
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
          
      - name: install pkg
        run: |
          cd lapce-volar
          npm install
          npx pkg vue-language-server.js --output-path ./dist --target x64,arm64
          
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: volar
          path: ${{ github.workspace }}/lapce-volar/dist/*
