# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the workflow will run
on:
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  windows:
    runs-on: ubuntu-latest
    container: ubuntu:18.04
    
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
          
      - name: install qemu
        run: apt install qemu binfmt-support qemu-user-static
        
      - name: Install ldid
        uses: MOZGIII/install-ldid-action@v1

      - name: install npm packages and pkg
        run: |
          cd lapce-volar
          npm install --production
          npx pkg vue-language-server.js --output-path ./dist --target x64,arm64
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: volar
          path: ${{ github.workspace }}/lapce-volar/dist/*
